### ISSUE TITLE
Dataset Acquisition

### ISSUE THREAD

**Issue by LCJHust** [valeoai/WoodScape#1]
Hello! I have followed the papers of your team, it was an excelltent work! Then, when will you release the dataset WoodScape? Hope for your reply!

**Comment by milliema** [comment]
Waiting for the release of dataset as well, hope to get the updates from author.

**Comment by buaaJeremyduan** [comment]
Any update? Waiting !!!

**Comment by G453** [comment]
Apologies for the delay, 

We have released the first version of the dataset, with annotations for 6 tasks.

RGB images
Semantic segmentation
2D bounding boxes
Instance segmentation
Motion segmentation
Previous images
CAN information
Lens soiling data and annotations

Coming Soon:
Calibration Information
Fisheye sythetic data with semantic annotations
Lidar and dGPS scenes

Please open a new issue for other queries. 
Thank You.
