### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by ygk09** [valeoai/WoodScape#10]
It is going to be 2021Q1 several days later. When to release the fisheye dataset ? Thank you very much.

**Comment by G453** [comment]
Apologies for the delay, 

We have released the first version of the dataset, with annotations for 6 tasks.

RGB images
Semantic segmentation
2D bounding boxes
Instance segmentation
Motion segmentation
Previous images
CAN information
Lens soiling data and annotations

Coming Soon:
Calibration Information
Fisheye sythetic data with semantic annotations
Lidar and dGPS scenes

Thank You.
