### ISSUE TITLE
The coordinate system of the 3D annotation in SynWoodScape

### ISSUE THREAD

**Issue by Sunyyyy** [valeoai/WoodScape#115]
I see that the 3d annotation PKL file in SynWoodScape recorded b-boxes' corner points. Do the keys in PKL correspond to all the objects in the scene that have not been filtered? And which coordinate system are the corner points in? Is it Lidar coordinate system?

**Comment by wangwz6666** [comment]
同问

**Comment by Sunyyyy** [comment]
已收到您的邮件！祝好~

**Comment by ARSekkat** [comment]
The PKL files contains the b-boxes in the world reference, all the bounding boxes of the vehicles are saved, they are not filtred.

**Comment by ARSekkat** [comment]
The PKL files contain the b-boxes in the world reference, all the bounding boxes are saved, they are not filtered.

**Comment by Sunyyyy** [comment]
> 同问

可以参考这个#107

**Comment by Sunyyyy** [comment]
> The PKL files contain the b-boxes in the world reference, all the bounding boxes are saved, they are not filtered.

Thanks for your reply！
