### ISSUE TITLE
A paper proposing a dataset accepted by ICCV yet dataset not released after two years, what a joke.

### ISSUE THREAD

**Issue by liuchang8am** [valeoai/WoodScape#12]

**Comment by G453** [comment]
Apologies for the delay, 

We have released the first version of the dataset, with annotations for 6 tasks.

RGB images
Semantic segmentation
2D bounding boxes
Instance segmentation
Motion segmentation
Previous images
CAN information
Lens soiling data and annotations

Coming Soon:
Calibration Information
Fisheye sythetic data with semantic annotations
Lidar and dGPS scenes

Please open a new issue for other queries. 
Thank You.
