### ISSUE TITLE
Can you provide the camera intrinsic parameters ?

### ISSUE THREAD

**Issue by henry121620** [valeoai/WoodScape#13]

**Comment by G453** [comment]
We are working on the camera calibration module. We will post the update on home page soon. Thank You.

**Comment by ctwitt** [comment]
The camera intrinsic parameters are now available at the [homepage](https://woodscape.valeo.com/download). Also we have [added an example](https://github.com/valeoai/WoodScape/tree/master/scripts/calibration) how to read the calibration files.

**Comment by sandeepnmenon** [comment]
How to construct the intrinsic matrix using the given intrinsic parameters
https://github.com/valeoai/WoodScape/blob/597d9dda472c09bafea58ea69853948d63197eca/scripts/calibration/front.json#L16-L26

I need the fx, fy, cx and cy values for the intrinsic matrix.

I can see that this line calculates cx and cy
https://github.com/valeoai/WoodScape/blob/597d9dda472c09bafea58ea69853948d63197eca/scripts/calibration/projection.py#L145
where `self._principle_point` has cx and cy values.

How to get fx and fy values?

Edit:
I understand from other issues that the model used for this paper is different from the OpenCV model and does not have fx, fy values. Even the k1,k2,k3 and k4 distortion parameters are different from that given by OpenCV.
