### ISSUE TITLE
semantic segmentation questions

### ISSUE THREAD

**Issue by purse1996** [valeoai/WoodScape#15]
Thank you for the released data. 
In woodscape paper, you provide semantic segmentation results of ENet as the baseline. Do you train and test only using 10 classes , consistent with the semantic tags you provided? 
Besides, the github readme says the remaining 1.8K test samples are held out for a benchmark. Will it be an online testing platform like cityscape? When is it released?

**Comment by G453** [comment]
Hi, The dataset went through some changes ( mentioned in our updated). So we need to re-evaluate the ENet baseline again. The 10 classes provided in the GDrive are for illustration purposes. You can generate semantic annotations for 40+ classes using the scripts provided. 

A competition is planned as part of our coming workshop. More details and workshop website will be updated soon. 

Thank You.

**Comment by purse1996** [comment]
Thank you for your reply.
What is the approximate time of the workshop?

**Comment by G453** [comment]
Hi Purse1996, 

Please find the details about the workshop here
