### ISSUE TITLE
some question in DirtyGAN

### ISSUE THREAD

**Issue by DannisZgggg** [valeoai/WoodScape#2]
hello！Here is a question about your latest paper DirtyGAN.
In this paper, how does the mask generated by VAE guide cycleGAN to generate the stains corresponding to the mask？
Looking forward to your relpy !!!

**Comment by G453** [comment]
We observed that the masks in the experimented dataset has low variance in the structure. Hence learning the masks directly caused the network to overfit to only few patterns. Hence we used VAE to generate more samples by navigating over the manifold. Please have a look at Figure 6. in our paper. 

Thank You.

**Comment by xuyanging** [comment]
The same doubt about the way you make use of generated masks. In fact, the C2S generator(you mentioned in paper) takes in both clean image and generated mask, but how does two inputs been trained with C2Sgenerator? concat them or dot or other ways?
