### ISSUE TITLE
Group of bicycles & motorcycles annotated as vehicles

### ISSUE THREAD

**Issue by ccqu** [valeoai/WoodScape#22]
Hi, in the annotation, group of bicycles / motorcycles are annotated as vehicles. Do you guys plan to correct this, or move them to something like group of bicycles / motorcycles?
![image](https://user-images.githubusercontent.com/23058357/115688181-31ee8a00-a35b-11eb-88ac-efd1b088c144.png)

**Comment by JanEGerken** [comment]
Hello,

I noticed the same thing. In the json instance annotations, the cases you mention are annotated as `other_wheeled_transport`. In the generation of the semantic segmentation masks, this then gets mapped to the `vehicle` class. However, there's also the class `grouped_vehicle` in the instance annotations, e.g. the parked cars in the distance in `02233_FV.png`, which gets mapped to `void`. What the reasoning for these labels and their distinction is, is not entirely clear to me, either.

Best,
Jan

**Comment by G453** [comment]
Hi ccqu & Jan,


@ccqn: Thanks for finding the issues. We are looking into the annotation errors. If there are is a need for re-annotation we will be doing it but it might take sometime. If you are participating in our CVPR workshop challenge, please continue to do so using the current annotations. 

@JanEGerken : other_wheeled_transport is to represent rare categories of transportation like pull carts ( commonly seen in Asia) etc. grouped_vehicle represent a group of vehicles ( overlapping vehicles). We mapped them to void. 

Thanks & Regards,
Ganesh

**Comment by JanEGerken** [comment]
Hi Ganesh,

Thanks for your prompt reply and pointing out the difference! However, I saw many instances of overlapping parked bikes being labeled as `other_wheeled_transport`, e.g. in `00275_MVL.png`, `00803_MVL.png`, `00984_MVR.png` and `01813_FV.png`.

Best,
Jan

**Comment by G453** [comment]
Hi Jan,
You are correct, we observed the same issue with 
00191_FV.png
00202_MVL.png
00219_MVR.png
00274_MVL.png etc.

'group of bicycles' also got annotated as 'other_wheeled_transport'. We will update the semantic annotations in GDrive (will move these groups to void). 
@ccqu this should fix the issues you raised. I post an update once things are ready. 

Thanks for the findings, highly appreciated.

**Comment by JanEGerken** [comment]
Hi Ganesh,

Great, thanks for your quick response!

**Comment by ccqu** [comment]
Hi Ganesh & Jan, thanks a lot for the quick help! :+1:

**Comment by G453** [comment]
Hi Jan and ccqu, 

We updated the labels in [GDrive](https://drive.google.com/drive/folders/1KFJlunkl-kBIArFOYGzkp7lTrzelOLhY?usp=sharing). 

Before Fix:
 
![wrong_ann](https://user-images.githubusercontent.com/7628224/116759507-6244c100-aa0a-11eb-989d-a411031e7558.PNG)

After Fix:

![correct_ann](https://user-images.githubusercontent.com/7628224/116759526-71c40a00-aa0a-11eb-9d00-9d263aa3bfb1.PNG)

**Comment by JanEGerken** [comment]
Hi Ganesh,

Great, thanks a lot for the quick fix!

Best,
Jan

**Comment by anhvth** [comment]
Hi, Ganesh
Is this change affect the current running challenge?

**Comment by G453** [comment]
Hi @anhvth ,
Yes, 
Participants have to use the new labels. we will notify everyone by email. 

Thanks,
Ganesh
