### ISSUE TITLE
Error in running semantic_map_generator

### ISSUE THREAD

**Issue by SutirthaChakraborty** [valeoai/WoodScape#23]
Trying to generate the semantic map. Getting this error.

`!python /content/WoodScape/scripts/semantic_map_generator.py --src_path /content/instance_annotations/ --dst_path /content/semantic_annotations/ --semantic_class_mapping  /content/WoodScape/scripts/configs/semantic_mapping_9_classes.json --instance_class_mapping /content/WoodScape/scripts/mappers/class_names.json`

Error I am getting: 
![image](https://user-images.githubusercontent.com/47362033/115976323-ba8c4680-a564-11eb-92bc-409ffdf79342.png)

**Comment by G453** [comment]
Hi @SutirthaChakraborty ,

Seems like the script generated the labels for 7208 annotations but crashed while processing a specific annotation file after that. Have you changed the class mappings? or trying to replicate our class mappings ?

If its for OmniCV Challenge, you don't need to generate the labels, we already provide ground truth required. 

Thanks, 
Ganesh

**Comment by SutirthaChakraborty** [comment]
Okay.
