### ISSUE TITLE
Green strips

### ISSUE THREAD

**Issue by JanEGerken** [valeoai/WoodScape#24]
Hello,

Thank you very much for sharing this amazing dataset! I noticed that there are two green strips, one at the top and one at the bottom, in each RGB image. They are a few pixels wide and contain some differently colored pixels as well. In the instance annotations they are labeled as `green_strip`. Could you explain what the purpose of these strips is? Can I just crop them during training?
I’m looking forward to your answer.

Best,
Jan

**Comment by G453** [comment]
Hi Jan,

1. For your experiments you can ignore or crop the green_strip area. It has no relation to the image content.  
2. This area got mapped to void in semantic segmentation labels. 
3. The predictions in that area ignored for evaluation in OmniCV challenge. 

Thanks,
Ganesh

**Comment by JanEGerken** [comment]
Hi Ganesh,

Okay, thanks for the clarification!

Best,
Jan
