### ISSUE TITLE
Dataset for same instance or different

### ISSUE THREAD

**Issue by TaheraTT** [valeoai/WoodScape#28]
Does this dataset contain front, rear, left and right view images of same instance or different instances?

**Comment by G453** [comment]
Hi Tahera,
They are of different instances. 

Thanks,
Ganesh

**Comment by TaheraTT** [comment]
Hi Ganesh,

Thanks for the reply. I was planning to stitch the images but looks like cant do that anymore with this. right?

Best Regards
Tahera

**Comment by G453** [comment]
Yes, its not possible to stitch the images for a 360 view.
