### ISSUE TITLE
mismatch in quaternion data for extrinsic parameters

### ISSUE THREAD

**Issue by TaheraTT** [valeoai/WoodScape#29]
The sample data shared in sample application and calibration readme files mention extrinsic rotation data in quaternion whereas the calibration data available released contains extrinsics similar to euler format.

How can i use this new data for getting rotation matrix? 

Best Regards
Tahera

**Comment by ctwitt** [comment]
Hello TaheraTT,

Thank you for your question. We are aware that the first release did not include the correct calibration files. This was fixed on 2021-04-27. Please download the corrected version from our website https://woodscape.valeo.com/download (there is some waiting time after clicking on download). 

  ```json
"extrinsic": {
    "quaternion": [
      0.5975199592616781,
      -0.5848284105884851,
      0.38861848213956907,
      -0.3871967249241737
    ],
    "translation": [
      3.7484,
      0.0,
      0.66103
    ]
  },
```

Best regards
Christian

**Comment by TaheraTT** [comment]
Hi Christian,

Thanks for the update. I have downloaded the new calibration files and verified the same.


Best Regards
Tahera
