### ISSUE TITLE
What is the timeline for dataset release?

### ISSUE THREAD

**Issue by kozzy** [valeoai/WoodScape#3]
two months past after the announcement of the release and iccv paper accepted...

**Comment by Nicholasli1995** [comment]
also interested in the timeline...

**Comment by zacmilan** [comment]
time pass by

**Comment by Mojojojooo** [comment]
Been waiting for it for a year.

**Comment by G453** [comment]
Apologies for the delay, 

We have released the dataset with 6-tasks. Please open a new issue for other queries. 

Thank You.

**Comment by G453** [comment]
Please go through readme.md for more information.
