### ISSUE TITLE
About OmniDet loss function

### ISSUE THREAD

**Issue by FlowEternal** [valeoai/WoodScape#41]
Thanks for your release of this dataset.

I read the OmniDet paper and find that you use auto-encoder to abstract feature to form feature-metric loss. 

Question One:
figure2 in your paper show that this feature is abstracted from the last output layer of decoder instead of from that of encoder, which is confusing. Is this just a drawing mistake or this feature Ft is really taken from the decoder?

Question Two:
The loss function for autoencoder only contain L_dis and L_cvt, but not L_reconstruction for autoencoder, which is different from that of "Feature-metric Loss for Self-supervised Learning of
Depth and Egomotion". is this just a writing mistake?

Hope you can solve these two question that puzzle me a lot

**Comment by rvarun7777** [comment]
Question One:
You are right, it is a drawing mistake, and Features are taken from the intermediate layers similar to Shu et al's work.

Question 2: 
yes, we do apply it on L_reconstruction as well. 

Thanks for pointing the mistakes out :) 
If you have my further doubts feel free to get in contact.

**Comment by FlowEternal** [comment]
> Question One:
> You are right, it is a drawing mistake, and Features are taken from the intermediate layers similar to Shu et al's work.
> 
> Question 2: 
> yes, we do apply it on L_reconstruction as well. 
> 
> Thanks for pointing the mistakes out :) 
> If you have my further doubts feel free to get in contact.

I am wondering do you ever plan to release the baseline code of FisheyeDistanceNet or the code of SVDistNet as announced in your abstract. If you do plan，then how long can this take？ I am now trying hard to reimplement the FisheyeDistanceNet but  it can not learn well. Maybe some important detail is missing. really appreciate it if you could release baseline code.

**Comment by FlowEternal** [comment]
I also contact you through your Google email but there seems to be no reply.

**Comment by rvarun7777** [comment]
Could you kindly send the email again?

**Comment by rvarun7777** [comment]
The code has been released. Thank you so much for being so patient :)
