### ISSUE TITLE
CANNOT download semantic segmentation annotations

### ISSUE THREAD

**Issue by ChulhoonJang** [valeoai/WoodScape#42]
First of all, thank you for sharing this invaluable dataset in public. 

I am trying to download the semantic segmentation annotations, but it fails.

I used this link 'https://drive.google.com/uc?export=download&id=1nNJMKz2Nx6pj6L2xlj_AWBhK6BGECSRD' and got the error like 

![image](https://user-images.githubusercontent.com/13134640/128241280-38b7c7f4-da34-4b21-869e-5d86d48a959c.png)

Could you take a look at this problem?

**Comment by G453** [comment]
Hi Chulhoon, 

Thanks for the appreciation and sorry for the inconvenience. Could you please try this link? : https://drive.google.com/drive/folders/1KFJlunkl-kBIArFOYGzkp7lTrzelOLhY 

Thanks & Regards,
Ganesh

**Comment by ChulhoonJang** [comment]
@G453 thank you so much. It works. appreciate it!

**Comment by jingyibo123** [comment]
@G453 It's probably a good idea to update the link in the [official website](https://woodscape.valeo.com/download)
