### ISSUE TITLE
Fisheye camera calibration method

### ISSUE THREAD

**Issue by DingGit** [valeoai/WoodScape#46]
Hi, thanks for the great work!
I have read the readme and example for calibration, and would like to produce the same calibration files/parameters as provided in the WoodScape dataset for my own collected fisheye images. 
Could you provide more details on how the calibration is done, and if possible some links to the model and method used for the calibration. Thank you!

**Comment by ctwitt** [comment]
Hello, 

unfortunately the calibration was done by the series production and cannot be easily reproduced or shared. However, with the mathematical background described in the calibration file, it should be possible to either write an own fit procedure to find the best calibration parameters or to transform another calibration into the one we use (4th order polynomial).
