### ISSUE TITLE
Are there video data? 

### ISSUE THREAD

**Issue by maudzung** [valeoai/WoodScape#49]
Dear authors,

Could you please provide fisheye videos data?

Many thanks!

**Comment by rvarun7777** [comment]
Hi Maudzung,

We have not released sequential frames as the data needs anonymization according to the EU GDPR rules.

**Comment by hitdshu** [comment]
> Hi Maudzung,
> 
> We have not released sequential frames as the data needs anonymization according to the EU GDPR rules.

Hi, thanks for your excellent work.  I'm also interested for benchmarking visual odometry using your video data. When might the video data be released? Thanks.

Deshun
