### ISSUE TITLE
How can we get access to the data?

### ISSUE THREAD

**Issue by Ariel-Yu** [valeoai/WoodScape#5]

**Comment by G453** [comment]
Apologies for the delay, 

We have released the first version of the dataset, with annotations for 6 tasks.

RGB images
Semantic segmentation
2D bounding boxes
Instance segmentation
Motion segmentation
Previous images
CAN information
Lens soiling data and annotations

You can download the datset from provided link @ readme. Please open a new issue for other queries. 

Thank You.
