### ISSUE TITLE
Asking about Camera Geometry Tensor

### ISSUE THREAD

**Issue by maudzung** [valeoai/WoodScape#51]
First of all, many thanks for your work.

I have investigated your implementation for OmniDet but I couldn't find the usage of Camera Geometry Tensor _Ct_ **(cam_conv=False)**.  Are there any reasons for it?

Thank you once again!

**Comment by rvarun7777** [comment]
Hi Maudzung,

We have released only the boilerplate version of our OmniDet framework. All the novel contributions listed in the paper have been held back due to IP reasons. Kindly check the [README](https://github.com/valeoai/WoodScape/blob/master/omnidet/README.md).
