### ISSUE TITLE
How to convert bbox_2d_annotations and segmentation annotations from fisheye-style format to cylindrical format?

### ISSUE THREAD

**Issue by LCJHust** [valeoai/WoodScape#54]
Hi:
    I haved changed fisheye image to cylindrical image and then I need to change the annotations correspondingly. So I used this code
`world_points = fisheye_cam.project_2d_to_3d(fisheye_points, norm=np.ones(fisheye_points.shape[0]))
            cyl_points = cylindrical_cam.project_3d_to_2d(world_points)`, which `fisheye_points` means the coordinates of 2d bounding boxes on raw fisheye images， `cyl_points` means ones on cylindrical images. But I got a unreasonable result when I visualized the annotations. Is there anything wrong with my code? 
Hope for reply! Thank you!

**Comment by ctwitt** [comment]
Hello, 
without trying out the code, It looks correct. Have you already solved the issue? Is it maybe a visualization issue?
Best
Christian

**Comment by LCJHust** [comment]
> 
Thank you for your reply. I have find the reason of the problem, bounding boxes at original fisheye images are not tightly surrounding the actual objects tightly,  when I convert them to cylindrical ones, it looks unreasonble. But there are not any wrong with code. Actually, we should convert segmentation annotations at fisheye images to cylindrial format, and then compute the maximum and minimum x and y coordinates to get the new bounding boxes correspond to cylindircal images, instead of convert original bbox's coordinates directly. 
![image](https://user-images.githubusercontent.com/28851156/148365389-1326f3dc-8802-493d-8ec4-7c8225ef9ce4.png)
![image](https://user-images.githubusercontent.com/28851156/148365425-d5beaa33-b910-4395-b7eb-13df778f5b12.png)
