### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by implus** [valeoai/WoodScape#6]
Dear authors, is the Dataset released now? 2020.4.11

Thanks very much if you can provide the link of Dataset as we are very interested in it for further research.

**Comment by G453** [comment]
Dear implus, 

Apologies for the delay, 

We have released the first version of the dataset with annotations for 6 tasks. Please go through our readme page to know more information about the dataset, licensing and download process. 

Please open a new issue for other queries. 
Thank You.
