### ISSUE TITLE
how can get intrinsic calibration k1、k2、k3、k4

### ISSUE THREAD

**Issue by wataincdx** [valeoai/WoodScape#62]
how can get intrinsic calibration k1、k2、k3、k4?
thank you!

**Comment by ctwitt** [comment]
Please download the calibration files from https://woodscape.valeo.com/download. There you find a calibration file for each image with the correct intrinsic parameters.

**Comment by DWendou** [comment]
> Please download the calibration files from https://woodscape.valeo.com/download. There you find a calibration file for each image with the correct intrinsic parameters.

What if it was my own fisheye camera? How do I get these four values? When OpenCV is used to calibrate the fisheye camera, k1,k2,p1,p2, two radial distortion parameters, two tangential distortion parameters, k3,k4 should be higher order radial distortion parameters.
