### ISSUE TITLE
Detection and semantic task,  the detection mAP is 11.3 and does not reach the mAP64 mentioned in the paper?

### ISSUE THREAD

**Issue by zjsun7** [valeoai/WoodScape#63]
Hi,

the train setting is same as your params.yaml，the semantic task iou is 58.7. How should I do to imporve the performance?

Looking forward to your reply, thanks!

**Comment by rvarun7777** [comment]
Hi,

Thanks for trying out the dataset and the code. Unfortunately, you can not reach the performance of the paper for the reasons stated in the [README](https://github.com/valeoai/WoodScape/blob/63554efe0f2df46a409cb6cc8b6893b3dc3dea2f/omnidet/README.md).

**Comment by zjsun7** [comment]
> Hi,
> 
> Thanks for trying out the dataset and the code. Unfortunately, you can not reach the performance of the paper for the reasons stated in the [README](https://github.com/valeoai/WoodScape/blob/63554efe0f2df46a409cb6cc8b6893b3dc3dea2f/omnidet/README.md).

Thank you very much for your reply, I hope your can open more data and source code in the future!
