### ISSUE TITLE
How could I use the polygon annotation to train the detection model?

### ISSUE THREAD

**Issue by zjsun7** [valeoai/WoodScape#64]

**Comment by rvarun7777** [comment]
Hi,

The current model predicts bounding boxes. If you need the model to predict polygons, some modifications will need to be done to the model, as explained in this [paper](https://openaccess.thecvf.com/content/WACV2021/papers/Rashed_Generalized_Object_Detection_on_Fisheye_Cameras_for_Autonomous_Driving_Dataset_WACV_2021_paper.pdf). It illustrates two methods for predicting polygons using polar and cartesian representations.
