### ISSUE TITLE
how do calibration 

### ISSUE THREAD

**Issue by wataincdx** [valeoai/WoodScape#68]
hi, "coefficients k1, k2, k3 and k4 are given in the calibration files",how can you get k1, k2, k3 and k4 by calibration ?

**Comment by rvarun7777** [comment]
This is obtained by an internal tool where the cameras are calibrated in a factory setting for the production use cases. The calibration tool can not be provided. For different projection model calibrations, you can check an open-source toolbox [kalibr](https://github.com/ethz-asl/kalibr)

**Comment by sandeepnmenon** [comment]
Can the calibration data be provided? If we get the checkerboard images, we can do the calibration ourselves in the model that we require. I require the OpenCV model of the fisheye calibration but the model used by the authors cannot be converted as per #58
