### ISSUE TITLE
Probleme in execution of omnidet quantitative inference scripts :  

### ISSUE THREAD

**Issue by Josk187** [valeoai/WoodScape#69]
Hi ,

in /omnidet/eval folder :

the  3 qualitiative inference scripts and **quantitative_detection.py** works correctly without bugs

But When trying to run the scripts:

**quantitative_motion.py**  and **quantitative_semantic.py** I have the same type of error  of type  : 

RuntimeError: stack expects each tensor to be equal size, but got [x, 6] at entry 0 and [y, 6] at entry 1 where x and y are random each time I try to  run the script

I use the same data/config.yaml as the provided on repository , I only changed the folder paths

**Comment by rvarun7777** [comment]
Hi,

Can you change the train flag to semantic in the [params](https://github.com/valeoai/WoodScape/blob/63554efe0f2df46a409cb6cc8b6893b3dc3dea2f/omnidet/data/params.yaml#L7) file and then run quantitative_semantic.py ?

**Comment by Josk187** [comment]
Yes it works, thanks :) . Ok, so we need to adapt the "train" flag according to the chosen inference script. (motion, semantic, or detection)
