### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by Karthikaddagadderamesh** [valeoai/WoodScape#7]
Hello,
I am interested to use the dataset for my research. When will it be available for use.

**Comment by MaxChanger** [comment]
It was mentioned that it would be released in Q4 2020 in this [Link ](https://sites.google.com/view/omnicv-cvpr2020/useful-datasets).🤒
may be coming soon

**Comment by G453** [comment]
Hi Karthik and Max, 

We have released the dataset with 6-tasks. Please go through our readme for more information. 

Apologies for the delay, 

We have released the first version of the dataset, with annotations for 6 tasks. Please open a new issue for other queries. 

Thank You.
