### ISSUE TITLE
[pre-trained weights requested]

### ISSUE THREAD

**Issue by CaptainEven** [valeoai/WoodScape#71]
Thank you for your excellent work! Could you please the pre-trained weights for testing? I can't find the link of pre-trained weights or checkpoint.

**Comment by rvarun7777** [comment]
### WoodScape Boilerplate Weights

[ResNet18, 544x288](https://drive.google.com/drive/folders/11NSTT4qygIgGRT8dit5E7x3XCC79Q0m-?usp=sharing)

[ResNet50, 544x288](https://drive.google.com/drive/folders/11jM1FmI0TBVYB-0Y9pRHHrlru4AWhbRd?usp=sharing)
