### ISSUE TITLE
i use normnet's result(estimated distance ) and the class "RadialPolyCamProjection" to project image pixels to point cloud ,with "Calibration Data" 's parameters, but i got strange and wrong point cloud, why?? 

### ISSUE THREAD

**Issue by MhinaX** [valeoai/WoodScape#81]

**Comment by FangJingYunner** [comment]
hello，does the normnet result accuracy？ l have trained this normnet model on kitti dataset，all setting is same as monodepth2 except the decoder part ,and l have got a very bad result. the abs_rel is arround 0.35.
