### ISSUE TITLE
dataset release

### ISSUE THREAD

**Issue by happyboyneu** [valeoai/WoodScape#9]
I'm very interested in your dataset. When will it be available? It was mentioned that it would be released in Q4 2020 in this [Link](https://sites.google.com/view/omnicv-cvpr2020/useful-datasets) .Will you release it on time?

**Comment by G453** [comment]
Apologies for the delay, 

We have released the first version of the dataset, with annotations for 6 tasks. Please feel free to open a new issue for other queries. 

Thank You.
