### ISSUE TITLE
calculate the angle_LUT in a wrong way?

### ISSUE THREAD

**Issue by victor000000** [valeoai/WoodScape#96]
https://github.com/valeoai/WoodScape/blob/3d774b8e59bbd87de6d71d002004257c136958b3/omnidet/data/generate_luts.py
in this file line 100, `a = np.roots([D[3], D[2], D[1], D[0], -_r])`
but int https://docs.opencv.org/4.x/db/d58/group__calib3d__fisheye.html
![image](https://user-images.githubusercontent.com/1636580/169306670-665e76ce-b809-4d5b-a0d3-8698c260ff3c.png)

I think it should be `a = np.roots([D[3], 0, D[2], 0, D[1], 0, D[0], -_r])`
Am I misunderstanding something?

**Comment by yudai-kato-aisin** [comment]
@victor000000 
Please check the following section of the paper of them.
https://arxiv.org/abs/1905.01489
> 2.1. Fisheye Camera Models

In addition, their coefficients include the focal length.

**Comment by victor000000** [comment]
Thanks, 
![image](https://user-images.githubusercontent.com/1636580/169439259-34a86e96-7af0-4155-9662-47d089ac9d11.png)
![image](https://user-images.githubusercontent.com/1636580/169441509-668f5fb4-1633-4d74-9a6d-75164d102db5.png)
